### ISSUE TITLE
Select option shows white in the list for non OSX browsers

### ISSUE THREAD

**Issue by DevNebulae** [fus-marcom/ci-react#13]
The `select` tag for the various categories of resources on the `/resources` route has a `color: white;` attribute applied to it. However, on non-OSX browsers this style rule will also be applied to the `option` tags encapsulated in the `select` tag. I suggest applying a `color: black;` attribute to the `option` tags or finding another method where the children ignore the parent's `color` attribute..

**Comment by JesseRWeigel** [comment]
Fixed: 82801db

Thanks for creating this issue!

**Comment by iamandrewluca** [comment]
@JesseRWeigel close the issue 🔥  : )

**Comment by JesseRWeigel** [comment]
Good call @iamandrewluca! I was going to close it, but must have gotten sidetracked.
