### ISSUE TITLE
Double cursor on resource card hover.

### ISSUE THREAD

**Issue by JesseRWeigel** [fus-marcom/ci-react#5]
The pointer and arrow style cursor both appear overlapping each other when hovering over a resource card on the resource page.

**Comment by iamandrewluca** [comment]
Can't be reproduced! : )

**Comment by JesseRWeigel** [comment]
I can't reproduce it now either. Closing for now. Hopefully I won't see it again.

**Comment by iamandrewluca** [comment]
Sometimes it also happens to me, but is not overlapping, just is staying one cursor constant.
