### ISSUE TITLE
Mobile keyboard stays visible even after touching search key

### ISSUE THREAD

**Issue by JesseRWeigel** [fus-marcom/ci-react#6]
When using the search on the resources page on a mobile phone. The virtual keyboard does not go away, as one would expect, when the search button on the keyboard is clicked.

It should go away when the search button is clicked or when the search icon in the input is clicked.

This was observed using Chrome for Android

**Comment by JonathanStine** [comment]
I found this wonderful stackoverflow page about this problem:
https://stackoverflow.com/questions/1109022/close-hide-the-android-soft-keyboard

I'll see if I can make a pull request with this fix.

**Comment by iamandrewluca** [comment]
@JonathanStine, unfortunately StackOverflow article is about Android SDK
